# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 76fbe4376f067d0c42420e46f118427801e5ef2e3cd39cc9019ea00ed2d64b28423f70a46162059df92dde14029251fc9745b717e9af3e4b3bc86470287ccbc8

test:
  secret_key_base: b00ab875f4c7cdbba0c0e01dee7f2fe7e002bfbb5984ac5ca1c55ff07c4576562d43290492a0f9605304aaeb2f767969e2ba5af9327131a4778791f80e079091

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
